// <auto-generated />
using Intersect.Server.Database.GameData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Intersect.Server.Migrations.Sqlite.Game
{
    [DbContext(typeof(SqliteGameContext))]
    [Migration("20250914001815_AddItemResistancesAndElementDamageBonus")]
    partial class AddItemResistancesAndElementDamageBonus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
