// <auto-generated />
using System;
using Intersect.Server.Database.PlayerData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Intersect.Server.Migrations.MySql.Player
{
    [DbContext(typeof(MySqlPlayerContext))]
    [Migration("20250215000000_AddedPropertiesToMarketSystem")]
    partial class AddedPropertiesToMarketSystem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally left empty. The full model snapshot is maintained separately.
        }
    }
}
