// <auto-generated />
using System;
using Intersect.Server.Database.PlayerData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Intersect.Server.Migrations.MySql.Player
{
    [DbContext(typeof(MySqlPlayerContext))]
    [Migration("20250817052544_AddBestiaryUnlocks")]
    partial class AddBestiaryUnlocks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            new Snapshot().BuildModel(modelBuilder);
        }

        private sealed class Snapshot : MySqlPlayerContextModelSnapshot
        {
            public new void BuildModel(ModelBuilder modelBuilder) => base.BuildModel(modelBuilder);
        }
    }
}

